#
# h2
#
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:~/.h2/data/fhbay-db;AUTO_SERVER=true;DB_CLOSE_DELAY=-1

#
# postgressql
#
# add postgres extension
#   ./mvnw quarkus:add-extension -D"extensions=quarkus-jdbc-postgresql"

# start postgres docker container:
# docker run --name fhbay-db -e POSTGRES_USER=fh -e POSTGRES_PASSWORD=fh -e POSTGRES_DB=fhbay-db --publish 5432:5432 -d postgres

#quarkus.datasource.db-kind=postgresql
#quarkus.datasource.username=fh
#quarkus.datasource.password=fh
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/fhbay-db
#quarkus.datasource.jdbc.max-size=10

#
# hibernate config
#
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=false